-- 0024_restore_legacy_core_table_grants.sql
-- Restore an explicit least-privilege table privilege contract for the
-- legacy core tables created by 0001_initial_schema.sql.
--
-- RLS remains the row-level authorization boundary.  This migration only
-- makes the existing policies reachable for current application workflows.
-- It does not change policies, roles, ownership, default privileges, or RLS.

-- Remove Supabase bootstrap/default privileges, including unnecessary
-- TRUNCATE, REFERENCES and TRIGGER privileges, before granting the exact
-- contract below.  Repeated REVOKE/GRANT statements are idempotent.
REVOKE ALL ON TABLE
  public.tenants,
  public.profiles,
  public.tenant_users,
  public.subscriptions,
  public.audit_logs,
  public.patients,
  public.doctors,
  public.appointments,
  public.chief_complaints,
  public.dental_charts,
  public.tooth_states,
  public.findings,
  public.treatment_plans,
  public.treatment_stages,
  public.documents,
  public.integration_tokens
FROM PUBLIC, anon, authenticated, service_role;

-- Authenticated application reads required to establish tenant context and
-- load the current Supabase-backed patient/schedule/clinical views.
GRANT SELECT ON TABLE public.tenants TO authenticated;
GRANT SELECT ON TABLE public.tenant_users TO authenticated;
GRANT SELECT ON TABLE public.doctors TO authenticated;
GRANT SELECT ON TABLE public.treatment_stages TO authenticated;

-- Current direct application write paths.  RLS continues to scope every row.
GRANT SELECT, INSERT, UPDATE ON TABLE public.patients TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.chief_complaints TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.dental_charts TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.tooth_states TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.findings TO authenticated;

-- AppointmentRepository currently performs direct CRUD.  DELETE remains
-- limited to clinic_owner/clinic_admin by the existing RLS policy.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.appointments TO authenticated;

-- Treatment-plan create/update remains RPC-only.  The current repository
-- needs direct SELECT plus admin/owner DELETE under the existing RLS policy.
GRANT SELECT, DELETE ON TABLE public.treatment_plans TO authenticated;

-- No authenticated grants are added for profiles, subscriptions, legacy
-- audit_logs, documents, or integration_tokens because the current browser
-- application has no direct table workflow for them.  Profile/membership QA
-- setup and integration/subscription administration use service_role.

-- service_role is intentionally limited to ordinary CRUD on this explicit
-- legacy table list.  It receives no TRUNCATE, REFERENCES or TRIGGER grant,
-- and no schema-wide/default privilege expansion.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
  public.tenants,
  public.profiles,
  public.tenant_users,
  public.subscriptions,
  public.audit_logs,
  public.patients,
  public.doctors,
  public.appointments,
  public.chief_complaints,
  public.dental_charts,
  public.tooth_states,
  public.findings,
  public.treatment_plans,
  public.treatment_stages,
  public.documents,
  public.integration_tokens
TO service_role;

-- All legacy IDs are UUIDs generated by gen_random_uuid(); migration 0001
-- creates no serial/identity sequences, so no sequence privilege is needed.
-- Existing helper-function EXECUTE grants are already hardened by migration
-- 0008 and are deliberately left unchanged.
